services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: otp-backend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017
      - NODE_ENV=production
      - CORS_ORIGIN=http://187.127.131.10
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=http://187.127.131.10:3000/api/v1
        - VITE_RAZORPAY_KEY=rzp_test_SRrZ8YKuF5tkyr
    container_name: lets-connect-client
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: otp-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
