import mongoose from "mongoose";

const doctorSchema = new mongoose.Schema({
  deal_id: { type: Number, unique: true },
  full_name: String,
  dob: Date,
  gender: String,
  city: String,
  other_city: String,
  preferred_working_locations: String,
  emergency_contact_person: String,
  primary_qualification: String,
  qualification_certificate: String,
  university_name: String,
  year_of_passing: String,
  specialization: String,
  other_qualification: String,
  specialization_certificate: String,
  branch: String,
  university_board: String,
  year_of_completion: String,
  medical_council_name: String,
  registration_number: String,
  registration_certificate: String,
  registration_validity: String,
  government_id_aadhaar: String,
  government_id_pan: String,
  cancelled_cheque_file: String,
  passport_photo: String,
  total_experience_years: String,
  years_post_specialization: String,
  current_employment_status: String,
  current_hospital_attachments: String,
  license_number: String,
  anaesthesiology: String,
  optional_expertise: String,
  availability_model: String,
  booking_notice_preference: String,
  emergency_on_call: String,
  expected_charges_per_case: String,
  emergency_charges: String,
  minimum_guarantee_requirement: String,
  account_number: String,
  ifsc_code: String,
  upi_id: String,
  professional_indemnity_insurance: String,
  insurance_provider: String,
  policy_number: String,
  upload_policy_copy: String,
  doctor_code: String,
}, { timestamps: true });

export default mongoose.model("Doctor", doctorSchema);
